-- Replace the picsum.photos stock images (real photos, but unrelated to the
-- actual property) and the still-broken storage.example.com home report
-- links with assets genuinely hosted in Supabase Storage: a branded
-- "Photo Pending" placeholder graphic per listing photo, and a real
-- single-page Home Report PDF per property that has one. Generated by
-- scripts/generate-property-media.mjs.

update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh12345-1.svg' where url = 'https://picsum.photos/seed/eh12345-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh12345-2.svg' where url = 'https://picsum.photos/seed/eh12345-2/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh23456-1.svg' where url = 'https://picsum.photos/seed/eh23456-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh67890-1.svg' where url = 'https://picsum.photos/seed/eh67890-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh67890-2.svg' where url = 'https://picsum.photos/seed/eh67890-2/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh78901-1.svg' where url = 'https://picsum.photos/seed/eh78901-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g56789-1.svg' where url = 'https://picsum.photos/seed/g56789-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g56789-2.svg' where url = 'https://picsum.photos/seed/g56789-2/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g67890-1.svg' where url = 'https://picsum.photos/seed/g67890-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/fk12345-1.svg' where url = 'https://picsum.photos/seed/fk12345-1/800/600';
update property_photos set url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/fk12345-2.svg' where url = 'https://picsum.photos/seed/fk12345-2/800/600';

update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/eh12345.pdf' where ref = 'EH12345';
update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/g34567.pdf' where ref = 'G34567';
update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/eh56789.pdf' where ref = 'EH56789';
update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/eh67890.pdf' where ref = 'EH67890';
update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/g56789.pdf' where ref = 'G56789';
update properties set home_report_url = 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/reports/g67890.pdf' where ref = 'G67890';
