-- Every property now gets at least one "Photo Pending" placeholder — having
-- some listings photographed and others blank read as broken rather than
-- deliberate, once most of the grid had real placeholder art. Generated by
-- scripts/generate-property-media.mjs.

insert into property_photos (agency_id, property_id, url, sort_order) values
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g34567-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh45678-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh45678-2.svg', 1),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000005', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh56789-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000005', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh56789-2.svg', 1),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000006', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g45678-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/ab12345-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh89012-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh89012-2.svg', 1),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000e', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/g78901-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000f', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh90123-1.svg', 0),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000f', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/eh90123-2.svg', 1),
  ('00000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000010', 'https://mzqqknlzbrtrdtotmgkv.supabase.co/storage/v1/object/public/property-media/photos/ab23456-1.svg', 0);
